[package]
name = "mark_one_game_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bevy = "0.6.0"
csv = "1.1.6"
pixels = "0.11.0"
winit = "0.27.5"
winit_input_helper = "0.13.0"