[package]
name = "materiel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"
csv = "1.1.6"
pixels = "0.9.0"
winit = "0.26.1"